name: Create Release (tag + full changelog)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "New version tag (e.g., v1.2.3)"
        required: true
        type: string

permissions:
  contents: write  # required to create tags & releases with GITHUB_TOKEN

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # we need tags/history for the changelog

      - name: Build release notes (all commits since previous tag)
        id: notes
        run: |
          set -euo pipefail
          TAG="${{ inputs.tag }}"
          # Previous tag if any
          LAST_TAG="$(git describe --tags --abbrev=0 2>/dev/null || true)"
          
          {
            echo "## Changes"
            if [ -z "${LAST_TAG:-}" ]; then
              # No previous tag → include full history
              git log --pretty=format:"- %s (%h)"
            else
              # Commits since previous tag
              git log "${LAST_TAG}..HEAD" --pretty=format:"- %s (%h)"
              echo
              echo "**Full diff**: https://github.com/${{ github.repository }}/compare/${LAST_TAG}...${TAG}"
            fi
          } > RELEASE_NOTES.md
          
          echo "last_tag=${LAST_TAG:-}" >> "$GITHUB_OUTPUT"

      - name: Create tag & GitHub Release (with notes)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${{ inputs.tag }}" \
            --title "${{ inputs.tag }}" \
            --notes-file RELEASE_NOTES.md \
            --target "${GITHUB_SHA}"